version: '3.8'

volumes:
  mariadb-data:

services:

  db:
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=mariadb
